version: "3.5"
services:
  core:
    image: "trueblocks/core:v0.50.0-beta"
    entrypoint: |
      bash -c "\
      while [ ! -f /configuration/entrypoint.sh ] \
      do \
          echo No configuration found. Please use TrueBlocks Configuration Tool first. \
          echo If you are using DAppNode, click Info tab above, then Settings link. \
          echo Will try to re-read the configuration in a few seconds \
          sleep 5 \
      done \
      . /configuration/configuration.sh && \
      sh /configuration/entrypoint.sh"
    ports:
      - "8080:8080/tcp"
    restart: unless-stopped
    volumes:
      - "configuration:/configuration"
      - "trueblocks:/root/.local/share/trueblocks"
  configure:
    image: "trueblocks/config:v0.44.0-beta"
    restart: unless-stopped
    volumes:
      - "configuration:/output"
volumes:
  configuration: {}
  trueblocks: {}
